### ISSUE TITLE
default port

### ISSUE THREAD

**Issue by bertvannuffelen** [mu-semtech/mu-cache#2]
Hi,

is the default port 5000 as the README says? In the Dockerfile only port 80 is public, not 5000.

kr,
Bert

**Comment by erikap** [comment]
Hi @bertvannuffelen, in code the port is set to 5000 by default in case the `PORT` environment variable is not set. As the `PORT` environment variable is set to 80 by default in the Dockerfile, it's confusing what the default port will be. I will update the default to 80 in code as well as in the Dockerfile.
